<?php
/**
 * @var Jleagle\Packages\Application\Views\LayoutView $this
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Packages</title>

  <link media="all" type="text/css" rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link media="all" type="text/css" rel="stylesheet" href="/static/css/jquery.select2.min.css">
  <link media="all" type="text/css" rel="stylesheet" href="/static/css/jquery.select2-bootstrap.css">
  <link media="all" type="text/css" rel="stylesheet" href="/static/css/main.css">

  <!--[if lt IE 9]>
  <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<body>

  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand">PHP-Packages</span>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav">
          <li class="<?= $this->getData('path') == ''?'active':'' ?>"><a href="/">Search</a></li>
          <li class="<?= $this->getData('path') == 'stats'?'active':'' ?>"><a href="/stats">Stats</a></li>
          <li class="<?= $this->getData('path') == 'info'?'active':'' ?>"><a href="/info">Info</a></li>
        </ul>

      </div>
    </div>
  </nav>

  <div class="container">
    <?= $this->content() ?>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script src="/static/js/jquery.select2.min.js"></script>
  <script src="/static/js/jquery.highlight.js"></script>
  <script src="/static/js/main.js"></script>

</body>
</html>
