<?php
/**
 * @var Jleagle\Packages\Application\Views\PackageIncludeView $this
 */
?>

<?php if($this->getPackage()['name']){ ?>

  <a href="/package/<?= $this->getPackage()['author'] ?>/<?= $this->getPackage()['name'] ?>" class="panel panel-info package-include">

    <div class="panel-heading">
      <span class="badge pull-right"><?= number_format($this->getPackage()['downloads_m']) ?></span>
      <h3 class="panel-title"><?= $this->getPackage()['author'] ?>/<?= $this->getPackage()['name'] ?> (<?= $this->getPackage()['type'] ?>)</h3>
    </div>

    <div class="panel-body">
      <?= $this->getPackage()['description'] . '&nbsp;' ?>
    </div>

  </a>

<?php }else{ ?>

  <div class="panel panel-info">

    <div class="panel-heading">
      <h3 class="panel-title">
        <?= $this->getPackage()['author'] ?>
        <?= $this->getPackage()['name'] ? $this->getPackage()['name'] : $this->getPackage()['pivot']->version ?></h3>
    </div>

  </div>

<?php } ?>
